### ISSUE TITLE
render doesn't work with variable - with syntax error: unexpected partial, expecting string

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [open2b/scriggo#958] opened 2024-12-02 03:35 UTC
I found a bug with render function, it doesn't work with variables, only if we pass static string, the requirement was to use dynamic render for SPA application where the template/html needs to de decided in runtime

here is the code, the workaround I found was created a custom function  to render partial from variable

the code below raise the exception, if you change from ` {{ render partial }}` to ` {{ renderPartial(partial) }}` it works

```go
package main

import (
	"bytes"
	"fmt"
	"github.com/open2b/scriggo"
	"github.com/open2b/scriggo/native"
	"log"
)

func main() {
	fsys := scriggo.Files{
		"index.html": []byte(`<!DOCTYPE html>
<html>
<head>
    <title>Renderizando Partial</title>
</head>
<body>
    <h1>welcome</h1>
	{% partial := "partial.html" %}
    {{ render partial }}
</body>
</html>`),
		"partial.html": []byte(`<p>partial content.</p>`),
	}

	opts := &scriggo.BuildOptions{
		Globals: native.Declarations{
			"renderPartial": func(name string) string {
				var buf bytes.Buffer
				partial, err := scriggo.BuildTemplate(fsys, name, nil)
				if err != nil {
					return fmt.Sprintf("error while load templates: %v", err)
				}
				err = partial.Run(&buf, nil, nil)
				if err != nil {
					return fmt.Sprintf("erro during rendering: %v", err)
				}
				return buf.String()
			},
		},
	}
	// Construindo o template principal
	template, err := scriggo.BuildTemplate(fsys, "index.html", opts)
	if err != nil {
		log.Fatal("Erro ao compilar o template: %v", err)
	}

	// Renderizando o template
	var buf bytes.Buffer
	err = template.Run(&buf, nil, nil)
	if err != nil {
		log.Fatalf("Erro ao executar o template: %v", err)
	}

	// Exibindo o HTML final
	fmt.Println(buf.String())
}
```

**Comment by gazerro** [comment] 2024-12-04 09:10
The `render` operator takes a constant string as its argument, not a string variable. This is the intended behavior and not a bug. Once a template is compiled, Scriggo no longer accesses the file system, and at runtime, it has no way to read the partial file to render dynamically.

The error you encountered is a syntax error returned by the `scriggo.BuildTemplate` method:

> syntax error: unexpected partial, expecting string

The solution you propose—implementing a dedicated builtin function—is indeed the correct way to handle this use case. Keep in mind that if you declare the builtin like this:

```go
func(env native.Env, name string) string
```

You can then use the `env.CallPath` method to handle both relative and absolute paths. 

I’ll close this issue for now, but feel free to reopen it if there’s anything else you’d like to discuss.

**Closed by gazerro** 2024-12-04 09:10 UTC
Labels: needsInvestigation
